(source gnu)
(source melpa)

(depends-on "better-defaults")
(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "magit")
(depends-on "popwin")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "undo-tree")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")

(depends-on "org")
(depends-on "deft")

(depends-on "evil")
(depends-on "evil-magit")
(depends-on "evil-surround")
(depends-on "evil-numbers")
(depends-on "evil-leader")
(depends-on "evil-nerd-commenter")
(depends-on "evil-matchit")
(depends-on "evil-exchange")
(depends-on "evil-args")

(depends-on "elpy")
(depends-on "ein")
(depends-on "pyvenv")
(depends-on "blacken")
(depends-on "jedi")
(depends-on "epc")
(depends-on "auto-complete")
(depends-on "autopair")
(depends-on "py-autopep8")

(depends-on "auto-yasnippet")
(depends-on "auto-complete-exuberant-ctags")
(depends-on "auto-complete-clang-async")
(depends-on "auto-complete-clang")
(depends-on "auto-complete-chunk")
(depends-on "auto-complete-c-headers")
(depends-on "auto-complete-auctex")

(depends-on "ess")

(depends-on "json-mode")
(depends-on "json-reformat")

(depends-on "js3-mode")
(depends-on "js2-refactor")
(depends-on "js2-mode")
(depends-on "js2-closure")

(depends-on "lua-mode")
